import { iconMap } from './icon-map.mjs';

// Retro 84: one bit per pixel. Black on white, a dithered grey desk,
// striped title bars with a close box and nothing else.
const B = '#000000';
const W = '#ffffff';
const GREY = '#808080';
const CHICAGO = '"OS Retro Chicago", Chicago, Charcoal, Geneva, sans-serif';
const GENEVA = '"OS Retro Geneva", Geneva, Verdana, sans-serif';
// Window bodies run at modern sizes, where a bitmap face at 9px would
// be scaled; the outline Geneva the system still ships reads as the
// same family there.
const BODY = 'Geneva, Verdana, "OS Retro Geneva", sans-serif';
const MONO = 'Monaco, "Courier New", monospace';

export default {
	manifest: {
		manifestVersion: 2,
		id: 'mmtr/retro-84',
		name: 'Retro 84',
		version: '1.0.0',
		author: 'Miguel Torres',
		description: 'One bit per pixel: a dithered grey desk, striped title bars with a close box, and type drawn on a grid. The first desktop most people ever saw.',
		preview: 'preview.svg',
	},
	fonts: [
		{ family: 'OS Retro Chicago', weight: '400', display: 'swap', src: [ 'fonts/os-retro-chicago.woff' ] },
		{ family: 'OS Retro Geneva', weight: '400', display: 'swap', src: [ 'fonts/os-retro-geneva.woff' ] },
	],
	tokens: {
		// --- Type ---
		'--os-font-smoothing': 'antialiased',
		'--os-font': GENEVA,
		'--os-titlebar-font': CHICAGO,
		'--os-ui-font': BODY,
		'--os-ui-font-mono': MONO,

		// --- Desk ---
		'--os-backstop': GREY,
		'--os-bg': GREY,
		'--os-fg': B,
		'--os-fg-muted': B,
		'--os-desk-ink-light': B,
		'--os-icon-image-size': '32px',
		'--os-icon-label-bg': W,
		'--os-icon-label-shadow': 'none',
		'--os-icon-label-font-size': '9px',
		'--os-icon-label-radius': '0px',
		'--os-icon-label-padding': '0 2px',
		'--os-icon-glyph-shadow': 'none',
		'--os-icon-hover-bg': 'transparent',
		'--os-tile-fg': B,
		'--os-tile-label-color': B,
		'--os-tile-label-shadow': 'none',
		'--os-tile-hover-bg': 'transparent',
		'--os-tile-selected-bg': 'transparent',
		'--os-tile-selected-ring-width': '0px',
		'--os-tile-label-font-size': '9px',
		'--os-tile-label-smoothing': 'antialiased',
		'--os-tile-label-weight': '400',
		'--os-tile-label-padding': '0 2px',
		'--os-tile-shortcut-radius': '0px',
		'--os-tile-shortcut-bg': '#ffffff',
		'--os-tile-shortcut-fg': '#000000',
		'--os-tile-shortcut-shadow': '0 0 0 1px #000000',
		'--os-tile-label-selected-bg': B,
		'--os-tile-label-selected-color': '#ffffff',
		'--os-tile-label-bg': W,

		// --- Window frame ---
		'--os-window-bg': W,
		'--os-window-border': B,
		'--os-window-border-width': '1px',
		'--os-window-radius': '0px',
		'--os-window-shadow': `1px 1px 0 ${ B }`,
		'--os-window-shadow-focused': `1px 1px 0 ${ B }`,
		'--os-window-reveal-surface': W,
		'--os-folder-window-bg': W,
		'--os-resize-color': 'transparent',
		// The last button on the bar (the window menu, or a window's own
		// button) sits 9px from the right edge; a top handle wider than
		// 11px would cover it.
		'--os-resize-top-size': '10px',
		// The era did not dim the windows behind; the title bar says it.
		'--os-fx-darken-brightness': '1',
		'--os-fx-darken-saturate': '1',

		// --- Title bar ---
		'--os-titlebar-bg': W,
		'--os-titlebar-bg-focused': W,
		'--os-titlebar-color': B,
		'--os-titlebar-color-focused': B,
		'--os-titlebar-height': '19px',
		'--os-titlebar-padding': '0 8px',
		'--os-titlebar-gap': '6px',
		'--os-titlebar-font-size': '12px',
		'--os-titlebar-font-weight': '400',
		'--os-titlebar-title-position': 'absolute',
		'--os-titlebar-title-left': '50%',
		'--os-titlebar-title-translate': '-50% 0',
		'--os-titlebar-title-max-width': 'calc( 100% - 96px )',
		'--os-titlebar-title-padding': '6px',
		// The plate stops a pixel short of the rule under the bar.
		'--os-titlebar-title-bg': `linear-gradient( ${ W } 0 18px, transparent 18px )`,
		'--os-titlebar-divider': 'transparent',
		'--os-titlebar-divider-unfocused': 'transparent',
		'--os-titlebar-activity-idle-color': 'transparent',
		'--os-titlebar-activity-display': 'none',
		'--os-titlebar-controls-order': '-1',
		'--os-titlebar-controls-gap': '0px',
		'--os-titlebar-minimize-display': 'none',
		'--os-titlebar-maximize-display': 'none',
		'--os-titlebar-fullscreen-display': 'none',
		'--os-titlebar-btn-width': '13px',
		'--os-titlebar-btn-height': '13px',
		'--os-titlebar-btn-icon-size': '13px',
		'--os-titlebar-btn-press-transform': 'none',
		'--os-titlebar-btn-color': B,
		// Under the pointer a box goes grey; the close box inverts.
		'--os-titlebar-btn-color-hover': B,
		'--os-titlebar-btn-bg-hover': GREY,
		'--os-titlebar-btn-bg-active': W,
		'--os-titlebar-btn-focused-color': B,
		'--os-titlebar-btn-focused-color-hover': B,
		'--os-titlebar-btn-focused-bg-hover': GREY,
		'--os-titlebar-btn-focused-bg-active': W,
		'--os-titlebar-close-bg-hover': B,
		'--os-titlebar-close-color-hover': W,
		'--os-titlebar-btn-focused-outline': B,
		'--os-titlebar-meta-btn-radius': '0px',
		'--os-titlebar-meta-icon-size': '11px',
		'--os-ui-btn-bg': W,
		'--os-ui-btn-radius': '0px',

		// --- Tab strip ---
		'--os-tabs-bg': W,
		'--os-tabs-bg-unfocused': W,
		'--os-tabs-color': B,
		'--os-tabs-active-bg': W,
		'--os-tabs-active-color': B,
		'--os-tabs-active-color-muted': B,
		'--os-tabs-rail-opacity': '0',

		// --- Dock: a white palette with a hard shadow ---
		'--os-dock-bg': W,
		'--os-dock-floating-bg': W,
		'--os-dock-border': B,
		'--os-dock-floating-border': B,
		'--os-dock-floating-border-top': B,
		'--os-dock-floating-highlight': 'transparent',
		'--os-dock-floating-shadow': 'transparent',
		'--os-dock-floating-radius': '0px',
		'--os-dock-floating-backdrop': 'none',
		'--os-dock-floating-padding': '2px 8px 4px',
		'--os-dock-icon-color': B,
		'--os-dock-icon-color-hover': B,
		'--os-dock-item-bg-hover': 'transparent',
		'--os-dock-item-bg-focused': 'transparent',
		'--os-dock-item-outline': B,
		'--os-dock-item-radius': '0px',
		'--os-dock-item-hover-transform': 'none',
		'--os-dock-item-press-transform': 'none',
		'--os-dock-active-indicator': B,
		'--os-dock-divider': B,
		'--os-dock-separator-width': '1px',
		'--os-dock-separator-height': '28px',
		'--os-dock-separator-margin': '8px',
		'--os-dock-separator-bg': B,
		'--os-dock-separator-shadow': 'none',
		'--os-dock-exit-radius': '0px',
		'--os-dock-exit-ring': B,
		'--os-dock-exit-ring-hover': B,
		'--os-dock-exit-icon': B,
		'--os-dock-exit-hover-transform': 'none',
		'--os-tooltip-bg': W,
		'--os-tooltip-fg': B,
		'--os-tooltip-border': `1px solid ${ B }`,
		'--os-tooltip-radius': '0px',
		'--os-tooltip-padding': '1px 4px',
		'--os-tooltip-font-size': '12px',
		'--os-tooltip-shadow': `1px 1px 0 ${ B }`,

		// --- The toolbar is the menu bar ---
		'--os-toolbar-bg': W,
		'--os-toolbar-fg': B,
		// The menu bar keeps the time at its right end.
		'--os-toolbar-clock-display': 'block',
		'--os-toolbar-icon': B,
		'--os-toolbar-hover-bg': B,
		'--os-toolbar-hover-fg': W,
		'--os-toolbar-shadow': `0 1px 0 ${ B }`,
		'--os-toolbar-font': CHICAGO,
		'--os-toolbar-font-size': '12px',
		// The face's caps sit a pixel higher in the line than the system
		// font's; a 2px taller line centres them on the icons.
		'--os-toolbar-line-height': '34px',
		'--os-toolbar-menu-bg': W,
		'--os-toolbar-menu-fg': B,
		'--os-toolbar-menu-fg-muted': B,
		'--os-toolbar-menu-hover-bg': B,
		'--os-toolbar-menu-hover-fg': W,
		'--os-toolbar-menu-shadow': `0 0 0 1px ${ B }, 2px 2px 0 1px ${ B }`,

		// --- Selected rows invert ---
		'--os-ui-tab-fill': B,
		'--os-ui-tab-wash': 'none',
		'--os-ui-tab-bloom-opacity': '0',
		'--os-ui-tab-edge-width': '0px',
		'--os-ui-tab-selected-fg': '#ffffff',

		// --- Dock flyouts: a pull-down menu, inverted under the pointer ---
		'--os-cn-surface': W,
		'--os-cn-fg': B,
		'--os-cn-radius': '0px',
		'--os-cn-shadow': `0 0 0 1px ${ B }, 2px 2px 0 1px ${ B }`,
		'--os-cn-divider': B,
		'--os-cn-legend': B,
		'--os-cn-backdrop': 'none',
		'--os-cn-spotlight': 'none',
		'--os-cn-sheen': 'none',
		'--os-cn-row-radius': '0px',
		'--os-cn-row-fill': `linear-gradient( ${ B }, ${ B } )`,
		'--os-cn-row-ink': W,
		'--os-cn-head-icon-radius': '0px',
		'--os-cn-head-icon-fill': 'none',
		'--os-cn-head-icon-shadow': 'none',
		'--os-cn-orbit': 'currentColor',
		'--os-cn-orbit-halo': 'none',
		'--os-cn-orbit-halo-hover': 'none',
		'--os-cn-beam': B,
		'--os-cn-font': CHICAGO,
		'--os-cn-font-size': '12px',
		'--os-cn-title-size': '12px',
		'--os-cn-title-weight': '400',

		// --- Body palette ---
		'--os-ui-bg': W,
		'--os-ui-surface': W,
		'--os-ui-surface-elevated': W,
		'--os-ui-surface-sunken': W,
		'--os-ui-surface-raised': W,
		'--os-ui-surface-subtle': 'transparent',
		'--os-ui-bg-subtle': 'transparent',
		'--os-ui-fg': B,
		'--os-ui-fg-muted': B,
		'--os-ui-fg-faint': GREY,
		'--os-ui-text-muted': B,
		'--os-ui-border': B,
		'--os-ui-border-strong': B,
		'--os-ui-hover': 'transparent',
		'--os-ui-scrim': 'transparent',
		'--os-ui-field-bg': W,
		'--os-ui-field-border': B,
		'--os-ui-field-fg': B,
		'--os-ui-field-radius': '0px',
		'--os-ui-text-field-bg': W,
		'--os-ui-text-field-border': `1px solid ${ B }`,
		'--os-ui-focus-ring-field': `0 0 0 1px ${ B }`,
		'--os-ui-table-bg': W,
		'--os-ui-table-header-bg': W,
		'--os-ui-table-border': B,
		'--os-ui-table-row-hover': 'transparent',
		'--os-ui-table-stripe': 'transparent',
		'--os-ui-card-bg': W,
		'--os-ui-card-radius': '0px',
		'--os-ui-card-radius-compact': '0px',
		'--os-ui-card-border': B,
		'--os-ui-card-border-hover': B,
		'--os-ui-card-shadow-hover': `1px 1px 0 ${ B }`,
		'--os-ui-button-bg': W,
		'--os-ui-button-bg-hover': W,
		'--os-ui-button-fg': B,
		'--os-ui-button-border': `1px solid ${ B }`,
		'--os-ui-button-border-radius': '8px',
		'--os-ui-button-shadow-active': `inset 0 0 0 1px ${ B }`,
		'--os-ui-button-press-transform': 'none',
		'--os-ui-button-font-weight': '400',
		'--os-ui-chip-radius': '0px',
		'--os-ui-badge-border-radius': '0px',
		'--os-ui-progress-radius': '0px',
		'--os-ui-progress-fill': B,
		'--os-ui-flyout-bg': W,
		'--os-ui-flyout-fg': B,
		'--os-ui-flyout-shadow': `1px 1px 0 ${ B }`,
		'--os-ui-modal-bg': W,
		'--os-ui-modal-fg': B,
		'--os-ui-modal-text': B,
		'--os-ui-modal-text-muted': B,
		'--os-ui-modal-surface': W,
		'--os-ui-modal-surface-elevated': W,
		'--os-ui-modal-field-bg': W,
		'--os-ui-modal-border': B,
		'--os-ui-modal-border-strong': B,
		'--os-ui-modal-hover': 'transparent',
		'--os-ui-modal-button-bg-hover': W,
		'--os-ui-confirm-dialog-bg': W,
		'--os-ui-confirm-dialog-fg': B,
		'--os-ui-confirm-dialog-fg-muted': B,
		'--os-ui-context-menu-bg': W,
		'--os-ui-context-menu-fg': B,
		'--os-ui-context-menu-fg-muted': GREY,
		'--os-ui-context-menu-separator-color': GREY,
		'--os-ui-selection-bg': B,
		'--os-ui-selection-fg': W,
		'--os-ui-holo-fill': B,
		'--os-ui-holo-ink': W,
		'--os-ui-holo-track': W,
		'--os-ui-holo-track-edge': B,
		'--os-ui-hero-mesh': W,

		// --- Widgets on the desk ---
		'--os-ui-color-surface': W,
		'--os-ui-color-text': B,
		'--os-ui-color-text-subtle': B,
		'--os-ui-color-border': B,
		'--os-widgets-add-bg': W,
		'--os-widgets-add-bg-hover': W,
		'--os-widgets-add-border': B,
		'--os-widget-card-backdrop': 'none',
		'--os-widget-card-border': `1px solid ${ B }`,
		'--os-widget-card-radius': '0px',
		'--os-widget-card-shadow': `1px 1px 0 ${ B }`,
		'--os-widget-card-shadow-hover': `1px 1px 0 ${ B }`,
	},
	icons: {
		...iconMap(),
		WINDOW_CONTROL_CLOSE: { type: 'image', path: 'chrome/glyph-none.svg' },
		WINDOW_CONTROL_MENU: { type: 'image', path: 'chrome/glyph-menu.svg' },
	},
	textures: {
		TITLEBAR: { type: 'image', path: 'chrome/titlebar.svg', size: 'auto 100%', repeat: 'repeat-x', position: 'left top' },
		TITLEBAR_FOCUSED: { type: 'image', path: 'chrome/titlebar-focused.svg' },
		TITLEBAR_BUTTON: { type: 'image', path: 'chrome/closebox.svg', size: '100% 100%', repeat: 'no-repeat' },
		TITLEBAR_BUTTON_PRESSED: { type: 'image', path: 'chrome/closebox-pressed.svg' },
	},
	wallpapers: {
		grey: { path: 'chrome/desk-gray.svg', label: 'Grey', size: 'auto', repeat: 'repeat', position: 'left top' },
	},
	recommendedOsSettings: {
		windowRadius: 'sharp',
		desktopLayout: 'unified',
		dockPlacement: 'bottom',
		dockSize: 'default',
		adminBarMode: 'static',
		windowReveal: 'none',
		wallpaper: 'grey',
		accentColor: B,
		dockRailRenderer: 'default',
		// No Mio and no widgets: the era had neither on the desk.
		navPlacement: { 'os-mio-toggle': 'hidden' },
		widgets: [],
	},
};
